//how to run program: node createfile.mjs <filename> <linesQty>
import fs from 'fs'
import path from 'path'

if (!process.argv[2] || !process.argv[3]) {
    console.log('you need to type arguments')
    process.exit(0)
}
let fileName = process.argv[2]
let linesQty = parseInt(process.argv[3])

if (isNaN(linesQty)) {
    console.log('Lines quantity must be a number')
    process.exit(0)
}

const writeStream = fs.createWriteStream(path.join('./files', fileName))

console.log('start', performance.now())
for (let i = 1; i <= linesQty; i++) {
    writeStream.write(`This a line number ${i} in the autogenerated file\n`)
}
console.log('end', performance.now())

writeStream.end(() => {
    console.log(`${fileName} is the autogenerated`)
})

setTimeout(() => console.log('settimeout', performance.now()), 0)
